### ISSUE TITLE
[Feature Request] Hide top bar and bottom bar on scroll

### ISSUE THREAD

**Issue by Donkey-Doug** [SchweGELBin/OpenBible2#4]
A large part of the display is used for static content. Please consider hiding these bars on scroll.

**Comment by SchweGELBin** [comment]
Thank you for the suggestion.

I adjusted the padding and removed the Navigation Bar entirely.
But it doesn't hide anything on scroll.

Closing it, because the main issue (Too much spaced used for other things than the text) is resolved.

Feel free to reopen it if you aren't happy with the current solution from `v1.0.0`.

Have a great day.
